sudo: required
language: php
dist: xenial
group: edge

services:
  - docker

php:
  - 7.2
  - 7.3
  - nightly

matrix:
  include:
    - env: LINT=1
      php: 7.3
    - env: COVERAGE=1
      php: 7.3

  allow_failures:
    - php: nightly

install:
  - composer self-update

before_script:
  - cp .env.testing .env
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer install --no-interaction
  - docker run -p 8529:8529 -e ARANGO_ROOT_PASSWORD=testing --name=arangodb3sbx arangodb/arangodb:3.5.1

script:
  - vendor/bin/phpunit -c phpunit.xml

notifications:
  email:
    on_success: change
    on_failure: always
