sudo: required
language: php
dist: xenial
group: edge

services:
  - docker

php:
  - 7.2
  - 7.3
  - 7.4

env:
  - ARANGO_SERVER=3.4.8
  - ARANGO_SERVER=3.5.3
  - ARANGO_SERVER=3.6.0

include:
  - env: LINT=1
    php: 7.3
  - env: COVERAGE=1
    php: 7.3

branches:
  only:
    - master
    - develop

install:
  - composer self-update

before_script:
  - cp .env.testing .env
  - echo -e "\nARANGODB_VERSION=$ARANGO_SERVER" >> .env
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer install --no-interaction
  - echo "docker pull arangodb/arangodb:$ARANGO_SERVER" | bash -
  - echo "docker run -d -p 8529:8529 -e ARANGO_ROOT_PASSWORD=testing arangodb/arangodb:$ARANGO_SERVER" | bash -
  - docker ps -a
  - sleep 30

script:
  - vendor/bin/phpunit -c phpunit.xml --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: change
    on_failure: always
