name: Building scripts

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

permissions:
  contents: read

jobs:
  arango_3_8:
    runs-on: ubuntu-latest
    services:
      arangodb:
        image: 'arangodb/arangodb:3.8.0'
        ports:
          - 8529:8529
        env:
          ARANGO_ROOT_PASSWORD: testing

    steps:
      - name: Add testing configuration
        run: cp .env.testing .env

      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: composer install --no-interaction

      - name: Wait ArangoDB to init
        run: sleep 30

      - name: Run tests suites
        run: vendor/bin/phpunit -c phpunit.xml